#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - curl

write_files:
  - content: |
      version: "3.7"

      services:

        proxy:
          image: nginx:latest
          restart: always
          container_name: nginx_proxy
          volumes:
            - ${PWD}/ghost.conf:/etc/nginx/conf.d/ghost.conf
          ports:
            - 80:80
          depends_on:
            - ghost
          networks:
            - nginx
          command: ["nginx", "-g", "daemon off;"]

        ghost:
          image: ghost:latest
          restart: always
          container_name: ghost
          volumes:
            - /mnt/${do_volume}/www_data:/var/lib/ghost/content
          environment:
            database__client: mysql
            database__connection__host: db-maria 
            database__connection__user: ghostuser
            database__connection__password: ${mysql_user_password}
            database__connection__database: ghost
            url: http://${cloudflare_zone}
          depends_on:
            - db-maria
          networks:
            - nginx
            - db-maria

        db-maria:
          image: mariadb:latest
          restart: always
          container_name: db_maria
          volumes:
            - /mnt/${do_volume}/mysql_data:/var/lib/mysql
          environment:
            MYSQL_DATABASE: ghost
            MYSQL_USER: ghostuser
            MYSQL_PASSWORD: ${mysql_user_password}
            MYSQL_ROOT_PASSWORD: ${mysql_password}
          networks:
            - db-maria
          expose:
            - 3306

      networks:
        db-maria:
        nginx:
    path: /opt/scripts/docker-compose.yml
  - content: |
      server {
        listen 80;
        listen [::]:80;
        server_name ${cloudflare_zone} www.${cloudflare_zone};
  
        gzip off;
  
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $http_host;
          proxy_pass http://ghost:2368;
          proxy_hide_header X-Powered-By;
        }
  
        location ~ /.well-known {
          allow all;
        }
      }
    path: /opt/scripts/ghost.conf
  - content: |
     #!/bin/sh
     echo "This is a change" >> test.txt
    path: /opt/scripts/hello_world.sh

runcmd:
- mkdir -p /opt/scripts
- mkdir -p /mnt/${do_volume}
- mount -o discard,defaults,noatime /dev/disk/by-id/scsi-0DO_Volume_${do_volume} /mnt/${do_volume}
- echo '/dev/disk/by-id/scsi-0DO_Volume_${do_volume} /mnt/${do_volume} ext4 defaults,nofail,discard 0 0' | sudo tee -a /etc/fstab
- mkdir -p /mnt/${do_volume}/www_data
- mkdir -p /mnt/${do_volume}/mysql_data
- cd /opt/scripts
- docker-compose up -d